### ISSUE TITLE
Unify errors wrongly if artifact name prefixes 

### ISSUE THREAD

**Issue by morazow** [exasol/artifact-reference-checker-maven-plugin#24]
### Situation

Artifact checker wrongly unifies the following in the user guide:

```
-For instance, `s3://exasol-artifacts/glue-connector/exasol-glue-connector-0.1.0-assembly.jar`.
+For instance, `s3://exasol-glue-connector-0.1.0-assembly.jar`.
```

### Acceptance Criteria

- It should only check for the artifact name part of the text

**Comment by morazow** [comment]
An example of this case:

![Screenshot from 2022-10-27 08-43-06](https://user-images.githubusercontent.com/916295/198210917-c09a8ea0-8ebf-4a8d-9c3c-c844ab658742.png)

**Comment by redcatbear** [comment]
The root cause for this is that the search for the artifact does not really resolve placeholders in the artifact name. Instead the search term uses a fuzzy regular expression.

```
[INFO] Detected artifact name:exasol-glue-connector-1.0.2-assembly.jar                         
[DEBUG] Generated pattern: \Qexasol-\E.*?\Q-\E.*?\Q-assembly.jar\E    
```
