### ISSUE TITLE
Optionally rate artifact-reference-checker:unify check as warning

### ISSUE THREAD

**Issue by kaklakariada** [exasol/artifact-reference-checker-maven-plugin#27]
PJ reported a use case in which the developer didn't plan to do a release immediately (for example when updating CI files) but bump the version in the `.pom` file so the current documentation file for the current changes (changelog) doesn't get overwritten.

After that PK forces to update the documentation references to this future version, thus referencing a yet unreleased version.

## Problem
References to  a yet unreleased version  might be confusing or wrong towards customers.

## Proposed mitigation
Reference checker should check if the release date in the latest changelog file is defined or not:

* If the changelog contains a concrete date (e.g. `# Project Keeper 2.9.16, released 2023-11-13`), work as normal
* If the changelog contains a dummy date (e.g. `# Project Keeper 2.9.16, released 2023-??-??`), reference checker logs a warning and does nothing

**Comment by pj-spoelders** [comment]
Thanks chipi! I like the proposed solution

**Comment by pj-spoelders** [comment]
Another idea is to add a flag/option that can be set for the maven plugin in the configuration section, like it's done here: https://github.com/spotify/fmt-maven-plugin/pull/153
At the moment to run project-keeper:fix when there's already a release of the current version you have to increase the version already. This is also not ideal but I guess this won't change. TBD'd.

**Comment by redcatbear** [comment]
People, please keep unreleased changes to a acceptable minimum, then we can live with the inconsistency. I am going to close this ticket. I understand where it comes from, but there are so many things that have priority over this issue.
